name: Core Tests

on: push

jobs:
  Core-Tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Run Tests
      working-directory: ./app/core
      run: gradle clean test
    - name: Test Reporter
      uses: dorny/test-reporter@v1.5.0
      with:
        name: Core Tests Results
        path: ./app/core/build/test-results/**/*.xml
        reporter: java-junit
